package com.springboothiber.entities;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor            //Argumented constructor 
@NoArgsConstructor             //Default constructor
@Data                          //Getter and Setter Method for all the data members
@Builder
@Entity                        //Specifying class is an entity
public class Student {         //creating Student class

	//Data members
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)    //making id as AutoGenerated 
	private int sid;
	private String sname;
	private String sage;
	private String scontact;

	@ManyToOne                 //making many students to opt one course
	@JoinColumn(name ="cid")
	private Courses scourse;
	
}
